kind: Deployment
apiVersion: apps/v1
metadata:
  name: flashsales-app
  namespace: default
  uid: 18968e17-9fdc-4e44-af5d-5f10da7ca4a9
  resourceVersion: '25702'
  generation: 5
  creationTimestamp: '2025-12-25T08:36:28Z'
  labels:
    appgroup: ''
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '1'
    description: ''
    workload.cce.io/swr-version: '[{"version":"Private Edition"}]'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:replicas: {}
      subresource: scale
    - manager: cfe-apiserver
      operation: Update
      apiVersion: apps/v1
      time: '2025-12-25T08:36:28Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:description: {}
            f:workload.cce.io/swr-version: {}
          f:labels:
            .: {}
            f:appgroup: {}
            f:version: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
                f:version: {}
            f:spec:
              f:containers:
                k:{"name":"container-1"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"PAAS_APP_NAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"PAAS_NAMESPACE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"PAAS_PROJECT_ID"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:imagePullSecrets:
                .: {}
                k:{"name":"default-secret"}: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:tolerations: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-12-25T09:33:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flashsales-app
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flashsales-app
        version: v1
    spec:
      containers:
        - name: container-1
          image: swr.tr-west-1.myhuaweicloud.com/dogancan-org/d-flashsale:v1
          env:
            - name: PAAS_APP_NAME
              value: flashsales-app
            - name: PAAS_NAMESPACE
              value: default
            - name: PAAS_PROJECT_ID
              value: 13cb1c6f4995452d87cc0a87e7ff4893
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: default-secret
      schedulerName: default-scheduler
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 5
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-12-25T08:36:29Z'
      lastTransitionTime: '2025-12-25T08:36:28Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "flashsales-app-8d7d79555" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-12-25T09:26:03Z'
      lastTransitionTime: '2025-12-25T09:26:03Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
