apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flashsales-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flashsales-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50